
// DOM Elements
const modelSelect = document.getElementById('modelSelect');
const taskSelect = document.getElementById('taskSelect');
const langSelect = document.getElementById('langSelect');
const maxTokensInput = document.getElementById('maxTokens');
const userPrompt = document.getElementById('userPrompt');
const systemPrompt = document.getElementById('systemPrompt');
const runBtn = document.getElementById('runBtn');
const outputArea = document.getElementById('outputArea');
const statusIndicator = document.getElementById('statusIndicator');
const latencyVal = document.getElementById('latencyVal');
const tokensVal = document.getElementById('tokensVal');
const codeBlock = document.getElementById('codeBlock');
const tabBtns = document.querySelectorAll('.tab-btn');

let currentLang = 'curl';

// Mock Responses
const MOCK_RESPONSES = {
    default: "This is a simulated response from the Crane v1.0 model. In a real environment, this would be generated by the model running on our sovereign infrastructure.",
    translate: {
        lg: "Mpulira bulungi nnyo. (Luganda translation)",
        sw: "Ninajisikia vizuri sana. (Swahili translation)",
        nyn: "Ninkyehurira gye munonga. (Runyankole translation)"
    },
    code: `def hello_world():\n    print("Hello Uganda!")`
};

// Event Listeners
modelSelect.addEventListener('change', updateState);
taskSelect.addEventListener('change', updateState);
langSelect.addEventListener('change', updateState);
userPrompt.addEventListener('input', updateCodePreview);
systemPrompt.addEventListener('input', updateCodePreview);
maxTokensInput.addEventListener('input', updateCodePreview);

tabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
        tabBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        currentLang = btn.dataset.lang;
        updateCodePreview();
    });
});

runBtn.addEventListener('click', async () => {
    // UI Loading State
    const originalText = runBtn.innerHTML;
    runBtn.disabled = true;
    runBtn.innerHTML = 'Running...';
    statusIndicator.innerText = 'Processing';
    statusIndicator.style.color = 'var(--accent-cyan)';
    outputArea.style.opacity = '0.5';

    // Simulate Network Delay (random between 300ms and 1500ms)
    const delay = Math.floor(Math.random() * 1200) + 300;

    await new Promise(resolve => setTimeout(resolve, delay));

    // Generate Response
    const task = taskSelect.value;
    const targetLang = langSelect.value;
    let result = MOCK_RESPONSES.default;

    if (task === 'translate' && MOCK_RESPONSES.translate[targetLang]) {
        result = MOCK_RESPONSES.translate[targetLang];
    } else if (userPrompt.value.toLowerCase().includes('code')) {
        result = MOCK_RESPONSES.code;
    }

    // Update UI
    outputArea.innerText = result;
    outputArea.style.opacity = '1';

    latencyVal.innerText = `${delay}ms`;
    tokensVal.innerText = Math.floor(result.length / 4); // Rough simuluation

    statusIndicator.innerText = 'Completed';
    statusIndicator.style.color = '#4ade80'; // Success green

    runBtn.disabled = false;
    runBtn.innerHTML = originalText;

    // Reset status
    setTimeout(() => {
        statusIndicator.innerText = 'Ready';
        statusIndicator.style.color = 'var(--text-secondary)';
    }, 2000);
});

function updateState() {
    const isTrans = taskSelect.value === 'translate';
    document.getElementById('langGroup').style.display = isTrans ? 'block' : 'none';
    updateCodePreview();
}

function updateCodePreview() {
    const model = modelSelect.value;
    const task = taskSelect.value;
    const maxTokens = maxTokensInput.value;
    const temp = document.getElementById('tempRange').value;
    const targetLang = langSelect.value;

    // Construct Input String based on task
    let promptText = escapeStr(userPrompt.value || "...");
    const system = systemPrompt.value ? `System: ${escapeStr(systemPrompt.value)}\\n` : "";

    if (task === 'translate') {
        promptText = `${system}Translate the following to ${targetLang}: ${promptText}`;
    } else {
        promptText = `${system}${promptText}`;
    }

    let code = "";

    switch (currentLang) {
        case 'curl':
            code = `curl https://api.crane.ai/crane/run \\
  -H "Authorization: Bearer $CRANE_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "model_id": "${model}",
    "input": "${promptText}",
    "options": {
      "temperature": ${temp},
      "max_tokens": ${maxTokens}
    }
  }'`;
            break;

        case 'js':
            code = `const res = await fetch("https://api.crane.ai/crane/run", {
  method: "POST",
  headers: {
    "Authorization": \`Bearer \${process.env.CRANE_API_KEY}\`,
    "Content-Type": "application/json"
  },
  body: JSON.stringify({
    model_id: "${model}",
    input: "${promptText}",
    options: {
      temperature: ${temp},
      max_tokens: ${maxTokens}
    }
  })
});

const data = await res.json();
console.log(data.output);`;
            break;

        case 'python':
            code = `import requests

url = "https://api.crane.ai/crane/run"
headers = {
  "Authorization": f"Bearer {API_KEY}",
  "Content-Type": "application/json"
}

payload = {
  "model_id": "${model}",
  "input": "${promptText}",
  "options": {
    "temperature": ${temp},
    "max_tokens": ${maxTokens}
  }
}

response = requests.post(url, json=payload, headers=headers)
print(response.json()["output"])`;
            break;
    }

    codeBlock.innerText = code;
}

function escapeStr(str) {
    if (!str) return "";
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

// Init
updateState();
